### ISSUE TITLE
[Bug] get_datetime_value fails to serialize empty string

### ISSUE THREAD

**Issue by michaeldcanady** [microsoft/kiota-serialization-json-python#258]
**Environment**

- Python Version: 3.11.8
- kiota-serialization-json version: 1.1.0
- OS: Windows 23H2

**Stack trace (if available)**
```python
Traceback (most recent call last):
  File "c:\Users\dmcanady\Projects\knowledge-editor\src\test.py", line 12, in <module>
    entry = node.get_object_value(ArticleItemResponse)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmcanady\Projects\knowledge-editor\.venv\Lib\site-packages\kiota_serialization_json\json_parse_node.py", line 212, in get_object_value
    self._assign_field_values(result)
  File "C:\Users\dmcanady\Projects\knowledge-editor\.venv\Lib\site-packages\kiota_serialization_json\json_parse_node.py", line 281, in _assign_field_values
    field_deserializer(JsonParseNode(field_value))
  File "c:\Users\dmcanady\Projects\knowledge-editor\src\servicenow\models\article_item_response.py", line 49, in <lambda>
    "result": lambda n: setattr(self, "result", n.get_object_value(Article))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmcanady\Projects\knowledge-editor\.venv\Lib\site-packages\kiota_serialization_json\json_parse_node.py", line 212, in get_object_value
    self._assign_field_values(result)
  File "C:\Users\dmcanady\Projects\knowledge-editor\.venv\Lib\site-packages\kiota_serialization_json\json_parse_node.py", line 281, in _assign_field_values
    field_deserializer(JsonParseNode(field_value))
  File "c:\Users\dmcanady\Projects\knowledge-editor\src\servicenow\models\article.py", line 138, in <lambda>
    self, "scheduled_publish_date", n.get_datetime_value()
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmcanady\Projects\knowledge-editor\.venv\Lib\site-packages\kiota_serialization_json\json_parse_node.py", line 93, in get_datetime_value
    datetime_obj = pendulum.parse(self._json_node, exact=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmcanady\Projects\knowledge-editor\.venv\Lib\site-packages\pendulum\parser.py", line 30, in parse
    return _parse(text, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmcanady\Projects\knowledge-editor\.venv\Lib\site-packages\pendulum\parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmcanady\Projects\knowledge-editor\.venv\Lib\site-packages\pendulum\parsing\__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmcanady\Projects\knowledge-editor\.venv\Lib\site-packages\pendulum\parsing\__init__.py", line 119, in _parse
    return _parse_common(text, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmcanady\Projects\knowledge-editor\.venv\Lib\site-packages\pendulum\parsing\__init__.py", line 171, in _parse_common
    return date(year, month, day)
           ^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
```

**Describe the bug**
when get_* is called it doesn't check if the node is empty or None (in this case it's an empty string "")

**To Reproduce**
```python
from __future__ import annotations
from typing import Any, Dict
from kiota_serialization_json.json_parse_node import JsonParseNode
from datetime import datetime
from typing import Any, Callable, Dict, Optional
from dataclasses import dataclass, field
from kiota_abstractions.serialization import (  # type:ignore
    AdditionalDataHolder,
    Parsable,
    ParseNode,
    SerializationWriter,
)
from kiota_abstractions.store import (  # type:ignore
    BackedModel,
    BackingStore,
    BackingStoreFactorySingleton,
)


@dataclass
class Article(AdditionalDataHolder, BackedModel, Parsable):

    # Stores model information.
    backing_store: BackingStore = field(
        default_factory=BackingStoreFactorySingleton(
            backing_store_factory=None
        ).backing_store_factory.create_backing_store,
        repr=False,
    )

    scheduled_publish_date: Optional[datetime] = None

    @staticmethod
    def create_from_discriminator_value(
        parse_node: Optional[ParseNode] = None,
    ) -> Article:
        """
        Creates a new instance of the appropriate class based on discriminator value
        param parse_node: The parse node to use to read the discriminator value and create the object
        Returns: Admin
        """
        if not parse_node:
            raise TypeError("parse_node cannot be null.")
        return Article()

    def get_field_deserializers(self) -> Dict[str, Callable[[ParseNode], None]]:
        """
        The deserialization information for the current model
        Returns: Dict[str, Callable[[ParseNode], None]]
        """
        fields: Dict[str, Callable[[ParseNode], None]] = {
        "scheduled_publish_date": lambda n: setattr(
                        self, "scheduled_publish_date", n.get_datetime_value()
                    ),
        }
        return fields

    def serialize(self, writer: SerializationWriter) -> None:
        """
        Serializes information the current object
        param writer: Serialization writer to use to serialize this model
        Returns: None
        """
        if not writer:
            raise TypeError("writer cannot be null.")

def sample_json() -> Dict[str, Any]:

    return {"scheduled_publish_date": ""}


node = JsonParseNode(sample_json())
entry = node.get_object_value(Article)
```

**Expected behavior**
If node is empty or None set it to None and return.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by michaeldcanady** [comment]
The issue is still ongoing, I would appreciate some feedback!
